### ISSUE TITLE
table.progress td.closedのbox-shadowが紛らわしい

### ISSUE THREAD

**Issue by vividtone** [farend/farend_bleuclair#1]
進捗率を表すバーにbox-shadowがついていますが、何らかの意味をもってグラフの塗り分けが行われているようにみえて紛らわしいです。

box-shadowを解除しても支障なさそうですがいかがでしょうか。

![progress-bar](https://cloud.githubusercontent.com/assets/114863/17727370/cb95f672-6493-11e6-8167-013ff675d5a2.png)

**Comment by junichi-ishikura** [comment]
@vividtone  そうですね、ここのbox-shadowは装飾的な意味合いだけでつけているので、紛らわしさを無くすために取り除いて良い気がします。ありがとうございます！

**Comment by junichi-ishikura** [comment]
b6bd4dd で対応しました。
